Added project for verifying
kirillparaschenko/TestmonitorTests pull request #5
Opened 2023-07-07 16:55 UTC by kirillparaschenko

Completed Core, PageObject, Builder, UI ProjectTestCreation,  API tests

2023-07-10 19:34 UTC, wildpioneer requested changes

2023-07-10 19:34 UTC, wildpioneer commented on TestmonitorTests/Core/ApiClient.cs
> +                MaxTimeout = 10000
Не сильно критично, но на будущее - такие параметры выносят в конфиг файл

2023-07-10 19:34 UTC, wildpioneer commented on TestmonitorTests/Core/DriverFactory.cs
> +            //chromeOptions.AddArguments("--headless");
Этот параметр тоже в конфиг вынести

2023-07-10 19:34 UTC, wildpioneer commented on TestmonitorTests/Core/WaitService.cs
> +            fluentWait.PollingInterval = TimeSpan.FromMilliseconds(1000);
Слишком большой интервал для FluentWait - стандартный у ExpectedWait - 500 милисек - а тут 1000

2023-07-10 19:34 UTC, wildpioneer commented on TestmonitorTests/Models/ProjectData.cs
> +        [JsonPropertyName("name")] public string Name { get; set; }
Лучшве в две строки - тогда визуально понятнее и чатаемость улучшается

2023-07-10 19:34 UTC, wildpioneer commented on TestmonitorTests/Services/ProjectService.cs
> +        public ProjectService(ApiClient apiClient) : base(apiClient)
Пустая строка

2023-07-10 19:34 UTC, wildpioneer commented on TestmonitorTests/Steps/ProjectSteps.cs
> +            return SettingsProjetsPage;
Пустая строка перед return

2023-07-10 19:34 UTC, wildpioneer commented on TestmonitorTests/Tests/API/ProjectAddTests.cs
> +            var testProject = new ProjectData()
Подготовку данных для тестов лучше всего вынести в какой-нибудь static Helper - потому что подготовдка данных может быть одинаковой для разных тестов

2023-07-10 19:34 UTC, wildpioneer commented on TestmonitorTests/Tests/API/ProjectGetTests.cs
> +                Assert.AreEqual(actualProject.Result.Content.ToString(), "{\n    \"message\": \"No query results for model [App\\\\Models\\\\Project] \"\n}");
В таких ситуациях необходимо активно использовать методы String.
Replace, Trim и т.д. - чтобы нормализировать актуальную строку

2023-07-11 15:31 UTC, kirillparaschenko commented on TestmonitorTests/Core/WaitService.cs
> +            fluentWait.PollingInterval = TimeSpan.FromMilliseconds(1000);
Испарвлено

2023-07-11 15:32 UTC, kirillparaschenko commented on TestmonitorTests/Models/ProjectData.cs
> +        [JsonPropertyName("name")] public string Name { get; set; }
Исправлено

2023-07-11 15:33 UTC, kirillparaschenko commented on TestmonitorTests/Services/ProjectService.cs
> +        public ProjectService(ApiClient apiClient) : base(apiClient)
Исправлено

2023-07-11 15:34 UTC, kirillparaschenko commented on TestmonitorTests/Steps/ProjectSteps.cs
> +            return SettingsProjetsPage;
Исправлено

2023-07-14 09:21 UTC, merged